tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "knazarov/qemu-virgl"
tap "planetscale/tap"
brew "anyenv"
brew "python@3.9"
brew "ghc"
brew "cabal-install"
brew "p11-kit"
brew "unbound"
brew "gnutls"
brew "emacs"
brew "cask"
brew "git"
brew "glib"
brew "gnu-sed"
brew "go"
brew "haskell-stack"
brew "python@3.10"
brew "ldns"
brew "libfido2"
brew "libssh"
brew "mas"
brew "meson"
brew "mysql-client"
brew "openssh"
brew "peco"
brew "postgresql@14"
brew "rename"
brew "wget"
brew "zip"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "knazarov/qemu-virgl/qemu-virgl"
brew "planetscale/tap/pscale"
cask "biscuit"
cask "clipy"
cask "docker"
cask "eul"
cask "hiddenbar"
cask "iterm2"
cask "kindle"
cask "kindle-previewer"
cask "notion"
cask "noxappplayer"
cask "owasp-zap"
cask "popclip"
cask "postman"
cask "slack"
cask "spotify"
cask "utm"
cask "visual-studio-code"
mas "GarageBand", id: 682658836
mas "GoodNotes", id: 1444383602
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "MindNode", id: 1289197285
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Spark", id: 1176895641
mas "Wake Up Time", id: 495945638
